alias ls='ls --color=auto'
alias ll='ls -l --group-directories-first -h'
alias rm='rm -I'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias less='less -r'
alias ack='ack-grep --color --pager="less -r"'
alias tmux='tmux -2'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
